#!/usr/bin/env bash

pid=$(pgrep -f "4-to_infinity_and_beyond")

if [ -n "$pid" ]; then
	kill "$pid"
	echo "Process '4-to_infinity_and_beyond' $pid has been stopped."
else
	echo "Process '4-to_infinity_and_beyond' is not running"
fi

