#!/usr/bin/env bash
#Bash script that displays all active IPv4 IPs on the machine it’s executed on.
#using ifconfig to get network interface information
ifconfig_output=$(ifconfig)

#Extract ipv4 address using grep and awk
ipv4_address=$(echo "$ifconfig_output" | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | awk '{print $2}' | grep -v '127.0.0.1')

#Display the ipv4 addresses
echo "$ipv4_address"

